export const DateFieldFragment = /* GraphQL */ `
  fragment DateFieldFragment on DateField {
    id
    adminLabel
    calendarIconType
    calendarIconUrl
    canPrepopulate
    cssClass
    databaseId
    dateFormat
    dateType
    defaultValue
    description
    descriptionPlacement
    displayOnly
    errorMessage
    inputName
    inputType
    isRequired
    label
    labelPlacement
    layoutGridColumnSpan
    layoutSpacerGridColumnSpan
    pageNumber
    placeholder
    shouldAllowDuplicates
    subLabelPlacement
    type
    value
    visibility
  }
`;
